name: Build and Formatting Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Spotless format check with Gradle Wrapper
        run: ./gradlew spotlessCheck

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Generate shaded jar
        run: ./gradlew shadowJar

      - name: Copy deployable artifacts
        run: |
          mkdir artifacts
          mv build/libs/collection-log-master-*-all.jar artifacts/collection-log-master.jar
          cp ".github/Run Client (Linux).sh" ".github/Run Client (Windows).bat" artifacts/

      - name: Upload deployable artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Runnable Client
          path: artifacts